tap "aws/tap"
tap "cloudflare/cloudflare"
tap "derailed/k9s"
tap "derailed/popeye"
tap "dtan4/tools"
tap "henkrehorst/php"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "roots/tap"
brew "openssl@1.1"
brew "bash-git-prompt", args: ["HEAD"]
brew "composer"
brew "dnsmasq", restart_service: true
brew "libyaml"
brew "docker-compose", link: false
brew "gobject-introspection"
brew "harfbuzz"
brew "libass"
brew "ffmpeg"
brew "gdk-pixbuf"
brew "geoip"
brew "git"
brew "git-gui"
brew "gnu-typist"
brew "httpd"
brew "jq"
brew "krb5"
brew "libdvdcss"
brew "libpq"
brew "pango"
brew "librsvg"
brew "libssh"
brew "libusb"
brew "lsusb"
brew "mailhog", restart_service: true
brew "mysql", restart_service: true
brew "mysql@5.7", restart_service: true
brew "nasm"
brew "node"
brew "php", link: false
brew "pipenv"
brew "portaudio"
brew "postgresql", restart_service: true
brew "postgresql@11"
brew "postgresql@12"
brew "potrace"
brew "pv"
brew "pwgen"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.8"
brew "qemu"
brew "qpdf"
brew "redis", restart_service: true
brew "rename"
brew "rsync"
brew "ruby"
brew "s3cmd"
brew "starship"
brew "testdisk"
brew "tree"
brew "wget"
brew "wp-cli"
brew "yarn"
brew "zlib"
brew "henkrehorst/php/valet-php@7.0"
brew "henkrehorst/php/valet-php@7.2"
brew "henkrehorst/php/valet-php@7.3", link: true
brew "henkrehorst/php/valet-php@7.4"
brew "roots/tap/trellis-cli", link: false
brew "roots/tap/trellis-cli-dev", args: ["HEAD"]
cask "google-cloud-sdk"
cask "kdiff3"
cask "keybase"
cask "osxfuse"
cask "vagrant"
cask "virtualbox"
