format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $cmd_duration\
  $line_break\
  $jobs\
  $character\
  $python\
  $sudo\
  """

[character]
success_symbol = "[•](bold green)"
error_symbol = "[•](bold red)"

[directory]
style = "bold blue"
truncate_to_repo = false

[git_branch]
style = "bold yellow"

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[python]
symbol = "👾 "
pyenv_version_name = true
